version: "3.8"

services: 

    application:
        build:
            context: .
            dockerfile: Dockerfile
        ports: 
            - 80:${SERVICE_PORT}
        links:
            - redis

    redis:
        image: bitnami/redis
        ports: 
            - ${REDIS_PORT}:6379
        environment: 
            - ALLOW_EMPTY_PASSWORD=yes
